spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/prac?serverTimezone=UTC
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html

mybatis-plus:
  type-aliases-package: com.howework0901.pojo
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
